/* The following code was generated by JFlex 1.4.1 on 2/21/24 8:20 PM */

// Alloy Analyzer 4 -- Copyright (c) 2006-2008, Felix Chang
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files
// (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify,
// merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
// OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

package edu.mit.csail.sdg.parser;

import edu.mit.csail.sdg.alloy4.Err;
import edu.mit.csail.sdg.alloy4.ErrorSyntax;
import edu.mit.csail.sdg.alloy4.Pos;
import edu.mit.csail.sdg.alloy4.Version;
import edu.mit.csail.sdg.ast.ExprConstant;
import edu.mit.csail.sdg.ast.ExprVar;
import java.util.List;
import java_cup.runtime.*;

/** Autogenerated by JFlex 1.4.1 */


public final class CompLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\77\1\111\1\66\1\0\1\111\1\110\16\77\4\0\1\100\1\1"+
    "\1\64\1\2\1\76\1\0\1\3\1\67\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\13\1\15\1\70\1\73\10\74\1\16\1\14\1\17"+
    "\1\20\1\12\1\0\1\21\6\72\2\107\1\57\3\107\1\105\1\102"+
    "\1\103\2\107\1\104\1\62\1\101\6\107\1\22\1\65\1\23\1\24"+
    "\1\71\1\106\1\31\1\32\1\36\1\41\1\42\1\56\1\61\1\44"+
    "\1\46\1\47\1\45\1\37\1\51\1\40\1\50\1\55\1\60\1\35"+
    "\1\33\1\34\1\43\1\54\1\107\1\52\1\53\1\63\1\25\1\26"+
    "\1\27\1\30\41\77\2\0\4\75\4\0\1\75\2\0\1\77\7\0"+
    "\1\75\4\0\1\75\5\0\27\75\1\0\37\75\1\0\u01ca\75\4\0"+
    "\14\75\16\0\5\75\7\0\1\75\1\0\1\75\21\0\160\77\5\75"+
    "\1\0\2\75\2\0\4\75\10\0\1\75\1\0\3\75\1\0\1\75"+
    "\1\0\24\75\1\0\123\75\1\0\213\75\1\0\5\77\2\0\236\75"+
    "\11\0\46\75\2\0\1\75\7\0\47\75\7\0\1\75\1\0\55\77"+
    "\1\0\1\77\1\0\2\77\1\0\2\77\1\0\1\77\10\0\33\75"+
    "\5\0\3\75\15\0\5\77\6\0\1\75\4\0\13\77\5\0\53\75"+
    "\37\77\4\0\2\75\1\77\143\75\1\0\1\75\10\77\1\0\6\77"+
    "\2\75\2\77\1\0\4\77\2\75\12\77\3\75\2\0\1\75\17\0"+
    "\1\77\1\75\1\77\36\75\33\77\2\0\131\75\13\77\1\75\16\0"+
    "\12\77\41\75\11\77\2\75\4\0\1\75\5\0\26\75\4\77\1\75"+
    "\11\77\1\75\3\77\1\75\5\77\22\0\31\75\3\77\104\0\1\75"+
    "\1\0\13\75\67\0\33\77\1\0\4\77\66\75\3\77\1\75\22\77"+
    "\1\75\7\77\12\75\2\77\2\0\12\77\1\0\7\75\1\0\7\75"+
    "\1\0\3\77\1\0\10\75\2\0\2\75\2\0\26\75\1\0\7\75"+
    "\1\0\1\75\3\0\4\75\2\0\1\77\1\75\7\77\2\0\2\77"+
    "\2\0\3\77\1\75\10\0\1\77\4\0\2\75\1\0\3\75\2\77"+
    "\2\0\12\77\4\75\7\0\1\75\5\0\3\77\1\0\6\75\4\0"+
    "\2\75\2\0\26\75\1\0\7\75\1\0\2\75\1\0\2\75\1\0"+
    "\2\75\2\0\1\77\1\0\5\77\4\0\2\77\2\0\3\77\3\0"+
    "\1\77\7\0\4\75\1\0\1\75\7\0\14\77\3\75\1\77\13\0"+
    "\3\77\1\0\11\75\1\0\3\75\1\0\26\75\1\0\7\75\1\0"+
    "\2\75\1\0\5\75\2\0\1\77\1\75\10\77\1\0\3\77\1\0"+
    "\3\77\2\0\1\75\17\0\2\75\2\77\2\0\12\77\1\0\1\75"+
    "\17\0\3\77\1\0\10\75\2\0\2\75\2\0\26\75\1\0\7\75"+
    "\1\0\2\75\1\0\5\75\2\0\1\77\1\75\7\77\2\0\2\77"+
    "\2\0\3\77\10\0\2\77\4\0\2\75\1\0\3\75\2\77\2\0"+
    "\12\77\1\0\1\75\20\0\1\77\1\75\1\0\6\75\3\0\3\75"+
    "\1\0\4\75\3\0\2\75\1\0\1\75\1\0\2\75\3\0\2\75"+
    "\3\0\3\75\3\0\14\75\4\0\5\77\3\0\3\77\1\0\4\77"+
    "\2\0\1\75\6\0\1\77\16\0\12\77\11\0\1\75\7\0\3\77"+
    "\1\0\10\75\1\0\3\75\1\0\27\75\1\0\12\75\1\0\5\75"+
    "\3\0\1\75\7\77\1\0\3\77\1\0\4\77\7\0\2\77\1\0"+
    "\2\75\6\0\2\75\2\77\2\0\12\77\22\0\2\77\1\0\10\75"+
    "\1\0\3\75\1\0\27\75\1\0\12\75\1\0\5\75\2\0\1\77"+
    "\1\75\7\77\1\0\3\77\1\0\4\77\7\0\2\77\7\0\1\75"+
    "\1\0\2\75\2\77\2\0\12\77\1\0\2\75\17\0\2\77\1\0"+
    "\10\75\1\0\3\75\1\0\51\75\2\0\1\75\7\77\1\0\3\77"+
    "\1\0\4\77\1\75\10\0\1\77\10\0\2\75\2\77\2\0\12\77"+
    "\12\0\6\75\2\0\2\77\1\0\22\75\3\0\30\75\1\0\11\75"+
    "\1\0\1\75\2\0\7\75\3\0\1\77\4\0\6\77\1\0\1\77"+
    "\1\0\10\77\22\0\2\77\15\0\60\75\1\77\2\75\7\77\4\0"+
    "\10\75\10\77\1\0\12\77\47\0\2\75\1\0\1\75\2\0\2\75"+
    "\1\0\1\75\2\0\1\75\6\0\4\75\1\0\7\75\1\0\3\75"+
    "\1\0\1\75\1\0\1\75\2\0\2\75\1\0\4\75\1\77\2\75"+
    "\6\77\1\0\2\77\1\75\2\0\5\75\1\0\1\75\1\0\6\77"+
    "\2\0\12\77\2\0\4\75\40\0\1\75\27\0\2\77\6\0\12\77"+
    "\13\0\1\77\1\0\1\77\1\0\1\77\4\0\2\77\10\75\1\0"+
    "\44\75\4\0\24\77\1\0\2\77\5\75\13\77\1\0\44\77\11\0"+
    "\1\77\71\0\53\75\24\77\1\75\12\77\6\0\6\75\4\77\4\75"+
    "\3\77\1\75\3\77\2\75\7\77\3\75\4\77\15\75\14\77\1\75"+
    "\17\77\2\0\46\75\1\0\1\75\5\0\1\75\2\0\53\75\1\0"+
    "\u014d\75\1\0\4\75\2\0\7\75\1\0\1\75\1\0\4\75\2\0"+
    "\51\75\1\0\4\75\2\0\41\75\1\0\4\75\2\0\7\75\1\0"+
    "\1\75\1\0\4\75\2\0\17\75\1\0\71\75\1\0\4\75\2\0"+
    "\103\75\2\0\3\77\40\0\20\75\20\0\125\75\14\0\u026c\75\2\0"+
    "\21\75\1\0\32\75\5\0\113\75\3\0\3\75\17\0\15\75\1\0"+
    "\4\75\3\77\13\0\22\75\3\77\13\0\22\75\2\77\14\0\15\75"+
    "\1\0\3\75\1\0\2\77\14\0\64\75\40\77\3\0\1\75\3\0"+
    "\2\75\1\77\2\0\12\77\41\0\3\77\2\0\12\77\6\0\130\75"+
    "\10\0\51\75\1\77\1\75\5\0\106\75\12\0\35\75\3\0\14\77"+
    "\4\0\14\77\12\0\12\77\36\75\2\0\5\75\13\0\54\75\4\0"+
    "\21\77\7\75\2\77\6\0\12\77\46\0\27\75\5\77\4\0\65\75"+
    "\12\77\1\0\35\77\2\0\13\77\6\0\12\77\15\0\1\75\130\0"+
    "\5\77\57\75\21\77\7\75\4\0\12\77\21\0\11\77\14\0\3\77"+
    "\36\75\15\77\2\75\12\77\54\75\16\77\14\0\44\75\24\77\10\0"+
    "\12\77\3\0\3\75\12\77\44\75\122\0\3\77\1\0\25\77\4\75"+
    "\1\77\4\75\3\77\2\75\11\0\300\75\47\77\25\0\4\77\u0116\75"+
    "\2\0\6\75\2\0\46\75\2\0\6\75\2\0\10\75\1\0\1\75"+
    "\1\0\1\75\1\0\1\75\1\0\37\75\2\0\65\75\1\0\7\75"+
    "\1\0\1\75\3\0\3\75\1\0\7\75\3\0\4\75\2\0\6\75"+
    "\4\0\15\75\5\0\3\75\1\0\7\75\16\0\5\77\32\0\5\77"+
    "\20\0\2\75\23\0\1\75\13\0\5\77\5\0\6\77\1\0\1\75"+
    "\15\0\1\75\20\0\15\75\3\0\33\75\25\0\15\77\4\0\1\77"+
    "\3\0\14\77\21\0\1\75\4\0\1\75\2\0\12\75\1\0\1\75"+
    "\3\0\5\75\6\0\1\75\1\0\1\75\1\0\1\75\1\0\4\75"+
    "\1\0\13\75\2\0\4\75\5\0\5\75\4\0\1\75\21\0\51\75"+
    "\u0a77\0\57\75\1\0\57\75\1\0\205\75\6\0\4\75\3\77\2\75"+
    "\14\0\46\75\1\0\1\75\5\0\1\75\2\0\70\75\7\0\1\75"+
    "\17\0\1\77\27\75\11\0\7\75\1\0\7\75\1\0\7\75\1\0"+
    "\7\75\1\0\7\75\1\0\7\75\1\0\7\75\1\0\7\75\1\0"+
    "\40\77\57\0\1\75\u01d5\0\3\75\31\0\11\75\6\77\1\0\5\75"+
    "\2\0\5\75\4\0\126\75\2\0\2\77\2\0\3\75\1\0\132\75"+
    "\1\0\4\75\5\0\51\75\3\0\136\75\21\0\33\75\65\0\20\75"+
    "\u0200\0\u19b6\75\112\0\u51cd\75\63\0\u048d\75\103\0\56\75\2\0\u010d\75"+
    "\3\0\20\75\12\77\2\75\24\0\57\75\1\77\4\0\12\77\1\0"+
    "\31\75\7\0\1\77\120\75\2\77\45\0\11\75\2\0\147\75\2\0"+
    "\4\75\1\0\4\75\14\0\13\75\115\0\12\75\1\77\3\75\1\77"+
    "\4\75\1\77\27\75\5\77\20\0\1\75\7\0\64\75\14\0\2\77"+
    "\62\75\21\77\13\0\12\77\6\0\22\77\6\75\3\0\1\75\4\0"+
    "\12\77\34\75\10\77\2\0\27\75\15\77\14\0\35\75\3\0\4\77"+
    "\57\75\16\77\16\0\1\75\12\77\46\0\51\75\16\77\11\0\3\75"+
    "\1\77\10\75\2\77\2\0\12\77\6\0\27\75\3\0\1\75\1\77"+
    "\4\0\60\75\1\77\1\75\3\77\2\75\2\77\5\75\2\77\1\75"+
    "\1\77\1\75\30\0\3\75\2\0\13\75\5\77\2\0\3\75\2\77"+
    "\12\0\6\75\2\0\6\75\2\0\6\75\11\0\7\75\1\0\7\75"+
    "\221\0\43\75\10\77\1\0\2\77\2\0\12\77\6\0\u2ba4\75\14\0"+
    "\27\75\4\0\61\75\u2104\0\u016e\75\2\0\152\75\46\0\7\75\14\0"+
    "\5\75\5\0\1\75\1\77\12\75\1\0\15\75\1\0\5\75\1\0"+
    "\1\75\1\0\2\75\1\0\2\75\1\0\154\75\41\0\u016b\75\22\0"+
    "\100\75\2\0\66\75\50\0\15\75\3\0\20\77\20\0\7\77\14\0"+
    "\2\75\30\0\3\75\31\0\1\75\6\0\5\75\1\0\207\75\2\0"+
    "\1\77\4\0\1\75\13\0\12\77\7\0\32\75\4\0\1\75\1\0"+
    "\32\75\13\0\131\75\3\0\6\75\2\0\6\75\2\0\6\75\2\0"+
    "\3\75\3\0\2\75\3\0\2\75\22\0\3\77\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\23\32\1\33\1\34\2\35\1\36\1\37"+
    "\1\40\1\34\1\41\2\0\1\42\1\43\1\0\1\44"+
    "\1\45\1\46\1\47\1\50\1\47\1\51\1\32\1\52"+
    "\14\32\1\53\6\32\1\54\3\32\1\51\12\32\1\55"+
    "\2\0\4\56\1\0\1\57\3\0\1\60\2\32\1\61"+
    "\1\36\1\62\1\63\1\64\1\65\1\66\2\32\1\67"+
    "\1\32\1\70\1\32\1\2\7\32\1\71\2\32\1\72"+
    "\2\32\1\60\1\73\6\32\1\74\1\32\1\75\1\76"+
    "\1\32\1\77\1\100\1\101\1\56\1\102\1\103\2\0"+
    "\1\34\2\32\1\104\1\105\1\32\1\106\1\107\1\110"+
    "\1\111\1\112\1\113\4\32\1\114\1\115\1\32\1\116"+
    "\1\32\1\117\1\120\1\32\1\121\2\32\1\0\2\32"+
    "\1\122\11\32\1\123\1\32\1\0\1\32\1\124\4\32"+
    "\1\125\1\32\1\126\2\32\1\127\1\0\2\32\1\130"+
    "\1\131\1\32\1\50\1\32\1\132\1\0\1\133\1\111"+
    "\2\32\1\0\1\32\1\117\1\0\1\71\4\0\1\134";

  private static int [] zzUnpackAction() {
    int [] result = new int[244];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\112\0\112\0\112\0\224\0\112\0\112\0\336"+
    "\0\u0128\0\112\0\u0172\0\u01bc\0\112\0\112\0\u0206\0\u0250"+
    "\0\u029a\0\u02e4\0\112\0\112\0\112\0\112\0\112\0\u032e"+
    "\0\112\0\112\0\u0378\0\u03c2\0\u040c\0\u0456\0\u04a0\0\u04ea"+
    "\0\u0534\0\u057e\0\u05c8\0\u0612\0\u065c\0\u06a6\0\u06f0\0\u073a"+
    "\0\u0784\0\u07ce\0\u0818\0\u0862\0\u08ac\0\u08f6\0\112\0\u0940"+
    "\0\u098a\0\112\0\112\0\112\0\u09d4\0\112\0\u0a1e\0\u0a68"+
    "\0\u0ab2\0\112\0\u0afc\0\112\0\112\0\112\0\u0b46\0\112"+
    "\0\112\0\112\0\u0b90\0\u0bda\0\u0c24\0\u0c6e\0\u0cb8\0\u0d02"+
    "\0\u0d4c\0\u0d96\0\u0de0\0\u0e2a\0\u0e74\0\u0ebe\0\u0f08\0\u0f52"+
    "\0\u0f9c\0\u0fe6\0\u1030\0\u107a\0\u10c4\0\u110e\0\u1158\0\u11a2"+
    "\0\u11ec\0\u1236\0\u1280\0\u06a6\0\u12ca\0\u1314\0\u135e\0\u13a8"+
    "\0\u13f2\0\u143c\0\u1486\0\u14d0\0\u151a\0\u1564\0\u15ae\0\u15f8"+
    "\0\u1642\0\u168c\0\u16d6\0\u1720\0\u176a\0\u17b4\0\112\0\u17fe"+
    "\0\u1848\0\u1892\0\112\0\u18dc\0\u1926\0\u06a6\0\u06a6\0\u06a6"+
    "\0\u06a6\0\u06a6\0\u06a6\0\u06a6\0\u1970\0\u19ba\0\u06a6\0\u1a04"+
    "\0\u06a6\0\u1a4e\0\u06a6\0\u1a98\0\u1ae2\0\u1b2c\0\u1b76\0\u1bc0"+
    "\0\u1c0a\0\u1c54\0\u1c9e\0\u1ce8\0\u1d32\0\u06a6\0\u1d7c\0\u1dc6"+
    "\0\u06a6\0\u06a6\0\u1e10\0\u1e5a\0\u1ea4\0\u1eee\0\u1f38\0\u1f82"+
    "\0\u06a6\0\u1fcc\0\u06a6\0\u06a6\0\u2016\0\u15ae\0\u1642\0\u16d6"+
    "\0\u2060\0\u1720\0\112\0\u20aa\0\u20f4\0\u17fe\0\u213e\0\u2188"+
    "\0\u06a6\0\u06a6\0\u21d2\0\u06a6\0\u06a6\0\u06a6\0\u221c\0\u06a6"+
    "\0\u06a6\0\u2266\0\u22b0\0\u22fa\0\u2344\0\u06a6\0\u06a6\0\u238e"+
    "\0\u06a6\0\u23d8\0\u2422\0\u06a6\0\u246c\0\u06a6\0\u24b6\0\u2500"+
    "\0\u254a\0\u2594\0\u25de\0\u06a6\0\u2628\0\u2672\0\u26bc\0\u2706"+
    "\0\u2750\0\u279a\0\u27e4\0\u282e\0\u2878\0\u06a6\0\u28c2\0\u290c"+
    "\0\u2956\0\u06a6\0\u29a0\0\u29ea\0\u2a34\0\u2a7e\0\u06a6\0\u2ac8"+
    "\0\u06a6\0\u2b12\0\u2b5c\0\u06a6\0\u2ba6\0\u2bf0\0\u2c3a\0\u06a6"+
    "\0\u06a6\0\u2c84\0\u06a6\0\u2cce\0\u06a6\0\u2d18\0\u06a6\0\u06a6"+
    "\0\u2d62\0\u2dac\0\u2df6\0\u2e40\0\u06a6\0\u2e8a\0\u06a6\0\u2ed4"+
    "\0\u2f1e\0\u2f68\0\u2fb2\0\112";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[244];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\2\46\1\47\1\46\1\50"+
    "\1\51\3\46\1\52\1\53\1\54\2\46\1\55\1\46"+
    "\1\56\1\2\1\57\1\2\1\60\2\46\2\61\2\46"+
    "\1\2\1\57\5\46\1\2\1\46\2\57\115\0\1\62"+
    "\114\0\1\63\112\0\1\64\113\0\1\65\1\66\23\0"+
    "\1\67\31\0\1\70\2\0\2\70\27\0\1\71\5\0"+
    "\1\72\77\0\1\73\6\0\1\65\106\0\1\74\3\0"+
    "\1\15\111\0\1\75\1\76\1\77\103\0\1\100\4\0"+
    "\1\101\120\0\1\102\114\0\1\46\1\103\1\104\3\46"+
    "\1\105\1\106\24\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\12\46\1\107\21\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\11\46\1\110\1\111\2\46"+
    "\1\112\1\46\1\113\14\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\13\46\1\114\20\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\12\46\1\115\21\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\13\46"+
    "\1\116\20\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\11\46\1\117\5\46\1\120\14\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\17\46\1\121\14\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\4\46"+
    "\1\122\10\46\1\123\16\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\6\46\1\124\1\125\11\46\1\126"+
    "\12\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\7\46\1\127\24\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\34\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\7\46\1\130\1\131\7\46\1\132\4\46"+
    "\1\133\6\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\4\46\1\134\2\46\1\135\14\46\1\136\7\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\17\46"+
    "\1\137\14\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\1\140\3\46\1\141\27\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\1\142\11\46\1\143\4\46"+
    "\1\144\14\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\7\46\1\145\24\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\3\46\1\146\30\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\2\0\64\56\1\147\1\150"+
    "\24\56\13\0\1\151\15\0\1\152\1\153\17\152\1\154"+
    "\12\152\2\0\1\152\1\61\1\155\1\152\2\61\1\0"+
    "\1\152\2\0\5\152\1\0\1\152\15\0\1\151\15\0"+
    "\34\152\2\0\1\152\1\61\1\155\1\152\2\61\1\0"+
    "\1\152\2\0\5\152\1\0\1\152\2\0\66\65\1\57"+
    "\21\65\1\57\1\65\43\0\1\156\61\0\1\151\54\0"+
    "\2\70\1\0\2\70\27\0\1\157\77\0\2\160\1\161"+
    "\3\160\1\162\103\160\12\0\1\163\130\0\2\46\1\164"+
    "\31\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\2\46\1\165\31\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\6\46\1\166\25\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\10\46\1\167\23\46\2\0"+
    "\11\46\1\0\5\46\1\0\1\46\33\0\3\46\1\170"+
    "\30\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\3\46\1\171\23\46\1\172\4\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\20\46\1\173\13\46\2\0"+
    "\11\46\1\0\5\46\1\0\1\46\33\0\30\46\1\174"+
    "\3\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\20\46\1\175\13\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\15\46\1\176\16\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\7\46\1\177\24\46\2\0"+
    "\11\46\1\0\5\46\1\0\1\46\33\0\11\46\1\200"+
    "\22\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\3\46\1\201\30\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\7\46\1\202\24\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\3\46\1\203\3\46\1\204"+
    "\24\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\17\46\1\205\14\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\2\46\1\206\31\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\2\46\1\207\31\46\2\0"+
    "\11\46\1\0\5\46\1\0\1\46\33\0\12\46\1\210"+
    "\21\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\1\211\2\46\1\212\7\46\1\213\10\46\1\214\7\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\15\46"+
    "\1\215\16\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\3\46\1\216\30\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\11\46\1\217\22\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\24\46\1\220\7\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\25\46"+
    "\1\221\6\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\11\46\1\222\22\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\11\46\1\223\22\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\10\46\1\224\23\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\4\46"+
    "\1\225\27\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\11\46\1\226\3\46\1\227\16\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\5\46\1\230\26\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\7\46"+
    "\1\231\22\46\1\232\1\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\4\46\1\233\27\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\3\46\1\234\30\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\4\46"+
    "\1\235\27\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\34\236\2\0\6\236\1\0\1\236\2\0\5\236"+
    "\1\0\1\236\2\0\66\56\1\0\23\56\70\0\1\237"+
    "\2\0\2\237\46\0\34\152\2\0\6\152\1\0\1\152"+
    "\2\0\5\152\1\0\1\152\33\0\34\152\2\0\1\152"+
    "\2\240\1\152\1\240\1\152\1\0\1\152\2\0\5\152"+
    "\1\0\1\152\33\0\2\241\3\152\1\241\2\152\2\241"+
    "\13\152\1\241\6\152\2\0\1\152\1\241\1\242\3\241"+
    "\1\0\1\152\2\0\5\152\1\0\1\152\15\0\1\151"+
    "\15\0\34\152\2\0\1\152\2\155\1\152\2\155\1\0"+
    "\1\152\2\0\5\152\1\0\1\152\36\0\1\243\55\0"+
    "\6\160\1\244\111\160\1\244\71\160\1\245\17\160\1\244"+
    "\6\160\1\246\74\160\31\0\3\46\1\247\30\46\2\0"+
    "\11\46\1\0\5\46\1\0\1\46\33\0\11\46\1\250"+
    "\22\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\11\46\1\251\22\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\2\46\1\252\31\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\5\46\1\253\26\46\2\0"+
    "\11\46\1\0\5\46\1\0\1\46\33\0\11\46\1\254"+
    "\22\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\11\46\1\255\22\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\24\46\1\256\7\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\16\46\1\257\15\46\2\0"+
    "\11\46\1\0\5\46\1\0\1\46\33\0\11\46\1\260"+
    "\22\46\2\0\11\46\1\0\5\46\1\0\1\46\33\0"+
    "\20\46\1\261\13\46\2\0\11\46\1\0\5\46\1\0"+
    "\1\46\33\0\5\46\1\262\26\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\11\46\1\263\22\46\2\0"+
    "\11\46\1\0\5\46\1\0\1\46\33\0\1\264\33\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\11\46"+
    "\1\265\22\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\23\46\1\266\10\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\7\46\1\267\24\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\6\46\1\270\25\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\7\46"+
    "\1\271\24\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\12\46\1\272\21\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\3\46\1\273\30\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\10\46\1\274\23\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\23\46"+
    "\1\275\10\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\3\46\1\276\30\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\32\46\1\277\1\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\15\46\1\300\16\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\2\242"+
    "\3\152\1\242\2\152\2\242\13\152\1\242\6\152\2\0"+
    "\1\152\1\242\1\152\3\242\1\0\1\152\2\0\5\152"+
    "\1\0\1\152\2\0\6\160\1\244\6\160\1\57\102\160"+
    "\1\244\72\160\1\301\10\160\31\0\4\46\1\302\27\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\4\46"+
    "\1\303\27\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\14\46\1\304\17\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\17\46\1\305\14\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\3\46\1\306\30\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\7\46"+
    "\1\307\24\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\12\46\1\310\21\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\5\46\1\311\26\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\15\46\1\312\16\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\6\46"+
    "\1\313\25\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\15\46\1\314\16\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\1\315\33\46\2\0\11\46\1\0"+
    "\5\46\1\0\1\46\33\0\22\46\1\316\11\46\2\0"+
    "\11\46\1\0\5\46\1\0\1\46\33\0\7\46\1\317"+
    "\24\46\2\0\11\46\1\0\5\46\1\0\1\46\2\0"+
    "\6\160\1\244\73\160\1\320\7\160\31\0\1\321\33\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\3\46"+
    "\1\322\30\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\15\46\1\323\16\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\6\46\1\324\25\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\10\46\1\325\23\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\2\46"+
    "\1\326\31\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\3\46\1\327\30\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\11\46\1\330\22\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\11\46\1\331\22\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\3\46"+
    "\1\332\30\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\3\46\1\333\30\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\30\46\1\334\3\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\2\0\6\160\1\244\74\160"+
    "\1\335\6\160\31\0\5\46\1\336\26\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\7\46\1\337\24\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\22\46"+
    "\1\340\11\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\2\46\1\341\31\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\3\46\1\342\30\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\2\46\1\343\31\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\15\46"+
    "\1\344\16\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\11\46\1\345\22\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\2\0\6\160\1\244\75\160\1\346\5\160"+
    "\31\0\3\46\1\347\30\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\33\0\3\46\1\350\30\46\2\0\11\46"+
    "\1\0\5\46\1\0\1\46\33\0\15\46\1\351\16\46"+
    "\2\0\11\46\1\0\5\46\1\0\1\46\33\0\17\46"+
    "\1\352\14\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\2\0\6\160\1\244\76\160\1\353\4\160\31\0\23\46"+
    "\1\354\10\46\2\0\11\46\1\0\5\46\1\0\1\46"+
    "\33\0\7\46\1\355\24\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\2\0\6\160\1\244\71\160\1\356\11\160"+
    "\31\0\11\46\1\357\22\46\2\0\11\46\1\0\5\46"+
    "\1\0\1\46\2\0\6\160\1\244\13\160\3\360\4\160"+
    "\33\360\1\160\1\360\3\160\2\360\6\160\7\360\10\160"+
    "\1\244\13\160\3\360\4\160\33\360\1\160\1\360\3\160"+
    "\2\360\5\160\1\361\7\360\4\160\1\362\3\160\1\244"+
    "\111\160\1\363\111\160\1\244\6\160\1\364\74\160";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12284];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\1\1\2\11\2\1\1\11\2\1\2\11"+
    "\4\1\5\11\1\1\2\11\24\1\1\11\2\1\3\11"+
    "\1\1\1\11\2\0\1\1\1\11\1\0\3\11\1\1"+
    "\3\11\45\1\2\0\4\1\1\0\1\11\3\0\1\11"+
    "\57\1\1\11\2\0\33\1\1\0\16\1\1\0\14\1"+
    "\1\0\10\1\1\0\4\1\1\0\2\1\1\0\1\1"+
    "\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[244];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
 public String alloy_filename="";
 public int alloy_lineoffset=0; // If not zero, it is added to the current LINE NUMBER
 public List<Object> alloy_seenDollar;
 public CompModule alloy_module;
 private final Pos alloy_here(String txt) {
    return new Pos(alloy_filename,yycolumn+1,yyline+1+alloy_lineoffset,yycolumn+txt.length(),yyline+1);
 }
 private final Symbol alloy_sym(String txt, int type) {
    Pos p = alloy_here(txt); return new Symbol(type, p, p);
 }
 private final Symbol alloy_string(String txt) throws Err {
    Pos p = alloy_here(txt);
    if (!Version.experimental) throw new ErrorSyntax(p, "String literal is not currently supported.");
    StringBuilder sb = new StringBuilder(txt.length());
    for(int i=0; i<txt.length(); i++) {
       char c = txt.charAt(i);
       if (c=='\r' || c=='\n') throw new ErrorSyntax(p, "String literal cannot span multiple lines; use \\n instead.");
       if (c=='\\') {
          i++;
          if (i>=txt.length()) throw new ErrorSyntax(p, "String literal cannot end with a single \\");
          c = txt.charAt(i);
          if (c=='n') c='\n'; else if (c!='\'' && c!='\"' && c!='\\') throw new ErrorSyntax(p, "String literal currenty only supports\nfour escape sequences: \\\\, \\n, \\\', and \\\"");
       }
       sb.append(c);
    }
    txt = sb.toString();
    if (txt.length()==2) throw new ErrorSyntax(p, "Empty string is not allowed; try rewriting your model to use an empty set instead.");
    return new Symbol(CompSym.STR, p, ExprConstant.Op.STRING.make(p, txt));
 }
 private final Symbol alloy_id(String txt) throws Err {
    Pos p=alloy_here(txt);
    if (alloy_seenDollar.size()==0 && txt.indexOf('$')>=0) alloy_seenDollar.add(null);
    return new Symbol(CompSym.ID, p, ExprVar.make(p,txt));
 }
 private final Symbol alloy_num(String txt, boolean isInt) throws Err {
    Pos p=alloy_here(txt);
    Number n=0;
    try {
        txt = txt.replaceAll("_","");
        n = isInt ? Integer.parseInt(txt) : Double.parseDouble(txt);
    } catch(NumberFormatException ex) {
       throw new ErrorSyntax(p, "The number "+txt+" " + ex);
    }
    return new Symbol(CompSym.NUMBER, p, ExprConstant.Op.NUMBER.make(p, n));
 }
 private final Symbol alloy_hexnum(String txt) throws Err {
    Pos p=alloy_here(txt);
    int n=0;
    try {
        txt = txt.substring(2).replaceAll("_","");
        n=Integer.parseInt(txt, 16);
    } catch(NumberFormatException ex) {
       throw new ErrorSyntax(p, "The hex number "+txt+" " + ex);
    }
    return new Symbol(CompSym.NUMBER, p, ExprConstant.Op.NUMBER.make(p, n));
 }
 private final Symbol alloy_binarynum(String txt) throws Err {
    Pos p=alloy_here(txt);
    int n=0;
    try {
        txt = txt.substring(2).replaceAll("_","");
        n=Integer.parseInt(txt, 2);
    } catch(NumberFormatException ex) {
       throw new ErrorSyntax(p, "The binary number "+txt+" " + ex);
    }
    return new Symbol(CompSym.NUMBER, p, ExprConstant.Op.NUMBER.make(p, n));
 }
 // Quantitative extension: t-norm imposed in file
 private String tnorm = "";
 private void tnorm(String txt) {
    if(tnorm.equals("")){
        tnorm = txt.substring(10);
        tnorm = tnorm.substring(0, tnorm.length() - 3).replaceAll("\\s+","");
        if(tnorm.equals("Godelian") ||
           tnorm.equals("Product")  ||
           tnorm.equals("Lukasiewicz") ||
           tnorm.equals("Drastic") ||
           tnorm.equals("Einstein")
           ){
            alloy_module.tnorm = tnorm;
        }else tnorm = "invalid"; // not a valid tnorm
    }
    // else does nothing
 }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CompLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public CompLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2276) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 31: 
          { return alloy_sym(yytext(), CompSym.STARSTAR    );
          }
        case 93: break;
        case 29: 
          { return alloy_num (yytext(), true);
          }
        case 94: break;
        case 92: 
          { tnorm (yytext());
          }
        case 95: break;
        case 4: 
          { return alloy_sym(yytext(), CompSym.AMPERSAND   );
          }
        case 96: break;
        case 52: 
          { return alloy_sym(yytext(), CompSym.SEQ         );
          }
        case 97: break;
        case 65: 
          { return alloy_binarynum (yytext());
          }
        case 98: break;
        case 40: 
          { return alloy_sym(yytext(), CompSym.IMPLIES     );
          }
        case 99: break;
        case 24: 
          { return alloy_sym(yytext(), CompSym.RBRACE      );
          }
        case 100: break;
        case 88: 
          { return alloy_sym(yytext(), CompSym.EXACTLY     );
          }
        case 101: break;
        case 1: 
          { throw new ErrorSyntax(alloy_here(" "), "Syntax error at the "+yytext()+" character. HEX: \\u"+Integer.toString(yytext().charAt(0),16)+")");
          }
        case 102: break;
        case 67: 
          { return alloy_sym(yytext(), CompSym.ALPHA       );
          }
        case 103: break;
        case 55: 
          { return alloy_sym(yytext(), CompSym.RUN         );
          }
        case 104: break;
        case 83: 
          { return alloy_sym(yytext(), CompSym.FUZZY       );
          }
        case 105: break;
        case 38: 
          { return alloy_sym(yytext(), CompSym.SHL         );
          }
        case 106: break;
        case 37: 
          { return alloy_sym(yytext(), CompSym.DOMAIN      );
          }
        case 107: break;
        case 62: 
          { return alloy_sym(yytext(), CompSym.SIGINT      );
          }
        case 108: break;
        case 25: 
          { return alloy_sym(yytext(), CompSym.TILDE       );
          }
        case 109: break;
        case 13: 
          { return alloy_sym(yytext(), CompSym.SEMICOLON   );
          }
        case 110: break;
        case 22: 
          { return alloy_sym(yytext(), CompSym.LBRACE      );
          }
        case 111: break;
        case 7: 
          { return alloy_sym(yytext(), CompSym.STAR        );
          }
        case 112: break;
        case 32: 
          { return alloy_sym(yytext(), CompSym.PLUSPLUS    );
          }
        case 113: break;
        case 60: 
          { return alloy_sym(yytext(), CompSym.FUN         );
          }
        case 114: break;
        case 87: 
          { return alloy_sym(yytext(), CompSym.STRING      );
          }
        case 115: break;
        case 57: 
          { return alloy_sym(yytext(), CompSym.EXH         );
          }
        case 116: break;
        case 58: 
          { return alloy_sym(yytext(), CompSym.INT         );
          }
        case 117: break;
        case 54: 
          { return alloy_sym(yytext(), CompSym.SIG         );
          }
        case 118: break;
        case 80: 
          { return alloy_sym(yytext(), CompSym.PRED        );
          }
        case 119: break;
        case 26: 
          { return alloy_id  (yytext());
          }
        case 120: break;
        case 64: 
          { return alloy_num (yytext(), false);
          }
        case 121: break;
        case 70: 
          { return alloy_sym(yytext(), CompSym.LONE        );
          }
        case 122: break;
        case 43: 
          { return alloy_sym(yytext(), CompSym.NO          );
          }
        case 123: break;
        case 9: 
          { return alloy_sym(yytext(), CompSym.COMMA       );
          }
        case 124: break;
        case 42: 
          { return alloy_sym(yytext(), CompSym.AS          );
          }
        case 125: break;
        case 69: 
          { return alloy_sym(yytext(), CompSym.THIS        );
          }
        case 126: break;
        case 14: 
          { return alloy_sym(yytext(), CompSym.SLASH       );
          }
        case 127: break;
        case 50: 
          { return alloy_sym(yytext(), CompSym.BUT         );
          }
        case 128: break;
        case 73: 
          { return alloy_sym(yytext(), CompSym.DISJ        );
          }
        case 129: break;
        case 45: 
          { return alloy_string(yytext());
          }
        case 130: break;
        case 34: 
          { return alloy_sym(yytext(), CompSym.SHA         );
          }
        case 131: break;
        case 41: 
          { return alloy_sym(yytext(), CompSym.OR          );
          }
        case 132: break;
        case 47: 
          { return alloy_sym(yytext(), CompSym.SHR         );
          }
        case 133: break;
        case 90: 
          { return alloy_sym(yytext(), CompSym.PRIVATE     );
          }
        case 134: break;
        case 33: 
          { return alloy_sym(yytext(), CompSym.ARROW       );
          }
        case 135: break;
        case 35: 
          { return alloy_sym(yytext(), CompSym.GTE         );
          }
        case 136: break;
        case 21: 
          { return alloy_sym(yytext(), CompSym.CARET       );
          }
        case 137: break;
        case 48: 
          { return alloy_sym(yytext(), CompSym.IFF         );
          }
        case 138: break;
        case 74: 
          { return alloy_sym(yytext(), CompSym.ELSE        );
          }
        case 139: break;
        case 3: 
          { return alloy_sym(yytext(), CompSym.HASH        );
          }
        case 140: break;
        case 12: 
          { return alloy_sym(yytext(), CompSym.DOT         );
          }
        case 141: break;
        case 23: 
          { return alloy_sym(yytext(), CompSym.BAR         );
          }
        case 142: break;
        case 85: 
          { return alloy_sym(yytext(), CompSym.EXPECT      );
          }
        case 143: break;
        case 8: 
          { return alloy_sym(yytext(), CompSym.PLUS        );
          }
        case 144: break;
        case 72: 
          { return alloy_sym(yytext(), CompSym.DROP        );
          }
        case 145: break;
        case 39: 
          { return alloy_sym(yytext(), CompSym.LTE         );
          }
        case 146: break;
        case 59: 
          { return alloy_sym(yytext(), CompSym.ONE         );
          }
        case 147: break;
        case 78: 
          { return alloy_sym(yytext(), CompSym.OPEN        );
          }
        case 148: break;
        case 66: 
          { return alloy_hexnum (yytext());
          }
        case 149: break;
        case 11: 
          { return alloy_sym(yytext(), CompSym.GT          );
          }
        case 150: break;
        case 86: 
          { return alloy_sym(yytext(), CompSym.MODULE      );
          }
        case 151: break;
        case 15: 
          { return alloy_sym(yytext(), CompSym.COLON       );
          }
        case 152: break;
        case 53: 
          { return alloy_sym(yytext(), CompSym.SUM         );
          }
        case 153: break;
        case 79: 
          { return alloy_sym(yytext(), CompSym.PART        );
          }
        case 154: break;
        case 17: 
          { return alloy_sym(yytext(), CompSym.EQUALS      );
          }
        case 155: break;
        case 89: 
          { return alloy_sym(yytext(), CompSym.EXTENDS     );
          }
        case 156: break;
        case 27: 
          { throw new ErrorSyntax(alloy_here(yytext()),"String literal is missing its closing \" character");
          }
        case 157: break;
        case 61: 
          { return alloy_sym(yytext(), CompSym.FOR         );
          }
        case 158: break;
        case 77: 
          { return alloy_sym(yytext(), CompSym.IDEN        );
          }
        case 159: break;
        case 16: 
          { return alloy_sym(yytext(), CompSym.LT          );
          }
        case 160: break;
        case 18: 
          { return alloy_sym(yytext(), CompSym.AT          );
          }
        case 161: break;
        case 36: 
          { return alloy_sym(yytext(), CompSym.RANGE       );
          }
        case 162: break;
        case 76: 
          { return alloy_sym(yytext(), CompSym.UNIV        );
          }
        case 163: break;
        case 2: 
          { return alloy_sym(yytext(), CompSym.NOT         );
          }
        case 164: break;
        case 51: 
          { return alloy_sym(yytext(), CompSym.SET         );
          }
        case 165: break;
        case 6: 
          { return alloy_sym(yytext(), CompSym.RPAREN      );
          }
        case 166: break;
        case 44: 
          { return alloy_sym(yytext(), CompSym.IN          );
          }
        case 167: break;
        case 82: 
          { return alloy_sym(yytext(), CompSym.CHECK       );
          }
        case 168: break;
        case 30: 
          { return alloy_sym(yytext(), CompSym.AND         );
          }
        case 169: break;
        case 68: 
          { return alloy_sym(yytext(), CompSym.SOME        );
          }
        case 170: break;
        case 81: 
          { return alloy_sym(yytext(), CompSym.FACT        );
          }
        case 171: break;
        case 10: 
          { return alloy_sym(yytext(), CompSym.MINUS       );
          }
        case 172: break;
        case 5: 
          { return alloy_sym(yytext(), CompSym.LPAREN      );
          }
        case 173: break;
        case 71: 
          { return alloy_sym(yytext(), CompSym.NONE        );
          }
        case 174: break;
        case 19: 
          { return alloy_sym(yytext(), CompSym.LBRACKET    );
          }
        case 175: break;
        case 20: 
          { return alloy_sym(yytext(), CompSym.RBRACKET    );
          }
        case 176: break;
        case 75: 
          { return alloy_sym(yytext(), CompSym.ENUM        );
          }
        case 177: break;
        case 49: 
          { return alloy_sym(yytext(), CompSym.ALL         );
          }
        case 178: break;
        case 91: 
          { return alloy_sym(yytext(), CompSym.ABSTRACT    );
          }
        case 179: break;
        case 84: 
          { return alloy_sym(yytext(), CompSym.ASSERT      );
          }
        case 180: break;
        case 63: 
          { throw new ErrorSyntax(alloy_here(yytext()),"String literal cannot be followed by a legal identifier character.");
          }
        case 181: break;
        case 56: 
          { return alloy_sym(yytext(), CompSym.LET         );
          }
        case 182: break;
        case 28: 
          { 
          }
        case 183: break;
        case 46: 
          { throw new ErrorSyntax(alloy_here(yytext()),"Name cannot start with a number.");
          }
        case 184: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   return new Symbol(CompSym.EOF, alloy_here(" "), alloy_here(" "));
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
